# Generated by Django 4.0 on 2021-12-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tile',
            new_name='title',
        ),
    ]
